### ISSUE TITLE
Weekly Scrum - March 26-April 2

### ISSUE THREAD

**Issue by Weebian** [Souheil-Yazji/Mini-Shopify#102]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
what will I do next week? (with link(s) to the relevant GitHub Issue(s))
what is holding me back? (if applicable)

**Comment by Weebian** [comment]
Done this week:
- Shop list doesn't reload on search: #90 
- Update shop list view to have sort by filter #81

For next week
- Update shop list query #80
- Hide search keyword when it's empty #101

Blockers:
none

**Comment by DwangDistracted** [comment]
Done this week:
- Create Tag/Categories fix

For next week
- About Page Fix.

Blockers:
Travis CI was broken/unavailable for the week. Was not able to merge anything until yesterday.

**Comment by Souheil-Yazji** [comment]
Done this week:
Update cart number: #105 
Closed - will not do #62 

For next week
Refactor Header Component #110

Blockers:
-

**Comment by mpfan** [comment]
Done this week:
Update inventory on checkout #98 
Image validation: #112 

For next week:
More validations
Style fixes

Blockers:
Ran out of CI credits

**Comment by dershao** [comment]
Done this week:
- #70 Add cookies to save shopping cart session
- #107 Fix shopping cart and checkout quantities

Next week:
- TBD

Blockers:
- Travis CI unavailable for a period time during week
