### ISSUE TITLE
Weekly Scrum - April 2-April 9

### ISSUE THREAD

**Issue by Weebian** [Souheil-Yazji/Mini-Shopify#103]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
what will I do next week? (with link(s) to the relevant GitHub Issue(s))
what is holding me back? (if applicable)

**Comment by Weebian** [comment]
Done this week
Update shop list query #80
Hide search keyword when it's empty #101

Blockers:
none

**Comment by DwangDistracted** [comment]
Done:
- #122 Added ability to delete a product

- #94 Updated the about page to display some statistics about the instance. Changed to text to detail the project.

Todo:
- Study for exams. drown my sorrows.

Blockers:
- none.

**Comment by dershao** [comment]
What have I done:
- #121 Add option to delete a shop
- #116 Add a search bar in product catalog to allow users to search for products

Blockers:
- None

**Comment by Souheil-Yazji** [comment]
What have I done:

#115 - removed login and signup page
#126 - removed case sensitivity from search bar
Blockers:

None

**Comment by mpfan** [comment]
What have I done:
#114 - allow other types of images 
#119 - fix image not updated when updating a shop

Blockers: None
